spring:
  datasource:
    url: jdbc:mariadb://svc.sel5.cloudtype.app:32067/dorandb?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwer1234
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://dorandb-mysql.cfiiptxn0fhq.ap-northeast-2.rds.amazonaws.com:3306/doran?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: admin
#    password: qwer1234

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

  mvc:
    pathmatch:
      matching-strategy: "ant_path_matcher"
