spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/test
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: test_user
#    password: test1234
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_url}:${DB_port}/{DB_dataBaseName}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_name}
    password: ${DB_password}

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

  mvc:
    pathmatch:
      matching-strategy: "ant_path_matcher"
